#!/bin/sh
# send confirmation email to instructor
#   confirms that individual student grade reports have been emailed
#     this is called in GradeBook.java

mail -s 'Grade Report Sent' david.w.lyons@gmail.com < gbk.indiv_report_top.txt

